import paris from '../../images/paris.jpg';
const blogsData = [
    {
      id: 1,
      title: 'Dublin',
      image: paris,
      description: 'Paris, often referred to as the City of Light, stands as a timeless symbol of elegance, culture, and romance. Nestled along the tranquil banks of the River Seine, this bustling metropolis is renowned for its rich history, breathtaking architecture, world-class art, and culinary delights.The citys iconic landmarks are emblematic of its grandeur. The Eiffel Tower, an engineering marvel and global icon, stands tall, offering panoramic views of the city from its lofty heights. The Notre-Dame Cathedral, despite the tragic fire that befell it, continues to hold a place in the heart of Parisians and visitors alike, with its Gothic spires and intricate rose windows leaving an indelible impression.Paris is synonymous with art and culture. The Louvre Museum, a treasure trove of human creativity, houses an unparalleled collection that spans centuries and civilizations. From the enigmatic smile of the Mona Lisa to the majestic Winged Victory of Samothrace, the Louvre is a testament to humanitys artistic achievements.Strolling through the cobbled streets of Montmartre or along the Champs-Élysées, visitors encounter a blend of old-world charm and modern vibrancy. Quaint cafés line the avenues, inviting passersby to savor freshly baked croissants while watching the world go by. The citys parks, like the Luxembourg Gardens and Parc des Buttes-Chaumont, provide tranquil oases amidst the urban hustle, where locals and tourists alike find respite.',
    },
    {
      id: 2,
      title: 'Paris',
      image: paris,
      description: 'Paris, often referred to as the City of Light, stands as a timeless symbol of elegance, culture, and romance. Nestled along the tranquil banks of the River Seine, this bustling metropolis is renowned for its rich history, breathtaking architecture, world-class art, and culinary delights.The citys iconic landmarks are emblematic of its grandeur. The Eiffel Tower, an engineering marvel and global icon, stands tall, offering panoramic views of the city from its lofty heights. The Notre-Dame Cathedral, despite the tragic fire that befell it, continues to hold a place in the heart of Parisians and visitors alike, with its Gothic spires and intricate rose windows leaving an indelible impression.Paris is synonymous with art and culture. The Louvre Museum, a treasure trove of human creativity, houses an unparalleled collection that spans centuries and civilizations. From the enigmatic smile of the Mona Lisa to the majestic Winged Victory of Samothrace, the Louvre is a testament to humanitys artistic achievements.Strolling through the cobbled streets of Montmartre or along the Champs-Élysées, visitors encounter a blend of old-world charm and modern vibrancy. Quaint cafés line the avenues, inviting passersby to savor freshly baked croissants while watching the world go by. The citys parks, like the Luxembourg Gardens and Parc des Buttes-Chaumont, provide tranquil oases amidst the urban hustle, where locals and tourists alike find respite.',
    },
    {
      id: 3,
      title: 'London',
      image: paris,
      description: 'Paris, often referred to as the City of Light, stands as a timeless symbol of elegance, culture, and romance. Nestled along the tranquil banks of the River Seine, this bustling metropolis is renowned for its rich history, breathtaking architecture, world-class art, and culinary delights.The citys iconic landmarks are emblematic of its grandeur. The Eiffel Tower, an engineering marvel and global icon, stands tall, offering panoramic views of the city from its lofty heights. The Notre-Dame Cathedral, despite the tragic fire that befell it, continues to hold a place in the heart of Parisians and visitors alike, with its Gothic spires and intricate rose windows leaving an indelible impression.Paris is synonymous with art and culture. The Louvre Museum, a treasure trove of human creativity, houses an unparalleled collection that spans centuries and civilizations. From the enigmatic smile of the Mona Lisa to the majestic Winged Victory of Samothrace, the Louvre is a testament to humanitys artistic achievements.Strolling through the cobbled streets of Montmartre or along the Champs-Élysées, visitors encounter a blend of old-world charm and modern vibrancy. Quaint cafés line the avenues, inviting passersby to savor freshly baked croissants while watching the world go by. The citys parks, like the Luxembourg Gardens and Parc des Buttes-Chaumont, provide tranquil oases amidst the urban hustle, where locals and tourists alike find respite.',
    },
    {
        id: 4,
        title: 'Paris',
        image: paris,
        description: "Paris, often referred to as the City of Light, stands as a timeless symbol of elegance, culture, and romance. Nestled along the tranquil banks of the River Seine, this bustling metropolis is renowned for its rich history, breathtaking architecture, world-class art, and culinary delights.The citys iconic landmarks are emblematic of its grandeur. The Eiffel Tower, an engineering marvel and global icon, stands tall, offering panoramic views of the city from its lofty heights. The Notre-Dame Cathedral, despite the tragic fire that befell it, continues to hold a place in the heart of Parisians and visitors alike, with its Gothic spires and intricate rose windows leaving an indelible impression.Paris is synonymous with art and culture. The Louvre Museum, a treasure trove of human creativity, houses an unparalleled collection that spans centuries and civilizations. From the enigmatic smile of the Mona Lisa to the majestic Winged Victory of Samothrace, the Louvre is a testament to humanitys artistic achievements.Strolling through the cobbled streets of Montmartre or along the Champs-Élysées, visitors encounter a blend of old-world charm and modern vibrancy. Quaint cafés line the avenues, inviting passersby to savor freshly baked croissants while watching the world go by. The citys parks, like the Luxembourg Gardens and Parc des Buttes-Chaumont, provide tranquil oases amidst the urban hustle, where locals and tourists alike find respite.",
      },
      {
        id: 5,
        title: 'Oslo',
        image: paris,
        description: 'Paris, often referred to as the City of Light, stands as a timeless symbol of elegance, culture, and romance. Nestled along the tranquil banks of the River Seine, this bustling metropolis is renowned for its rich history, breathtaking architecture, world-class art, and culinary delights.The citys iconic landmarks are emblematic of its grandeur. The Eiffel Tower, an engineering marvel and global icon, stands tall, offering panoramic views of the city from its lofty heights. The Notre-Dame Cathedral, despite the tragic fire that befell it, continues to hold a place in the heart of Parisians and visitors alike, with its Gothic spires and intricate rose windows leaving an indelible impression.Paris is synonymous with art and culture. The Louvre Museum, a treasure trove of human creativity, houses an unparalleled collection that spans centuries and civilizations. From the enigmatic smile of the Mona Lisa to the majestic Winged Victory of Samothrace, the Louvre is a testament to humanitys artistic achievements.Strolling through the cobbled streets of Montmartre or along the Champs-Élysées, visitors encounter a blend of old-world charm and modern vibrancy. Quaint cafés line the avenues, inviting passersby to savor freshly baked croissants while watching the world go by. The citys parks, like the Luxembourg Gardens and Parc des Buttes-Chaumont, provide tranquil oases amidst the urban hustle, where locals and tourists alike find respite.',
      },
  ];
  
  export default blogsData;
  